{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-data",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-1.0.5.aar",
          "url": "ui-tooling-data-1.0.5.aar",
          "size": 29158,
          "sha512": "3421715f2dde117ec72465cd29dccdf12169b22eb9fb51c4285f22d53932b090e5f46ec06c8253ae266d3b23c693e08d79bff640ccad0deb6fbf4ee8ff197bfd",
          "sha256": "1c391b3a12e357cd46d31444b3402fcd8c5a48c18cd2b5a31dadef7379c22abf",
          "sha1": "b1ceae44255ef19b99d19a8af3502fdfb7121bfe",
          "md5": "0ffb6e79c1a9ca820b81ec971c8e1f00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-1.0.5.aar",
          "url": "ui-tooling-data-1.0.5.aar",
          "size": 29158,
          "sha512": "3421715f2dde117ec72465cd29dccdf12169b22eb9fb51c4285f22d53932b090e5f46ec06c8253ae266d3b23c693e08d79bff640ccad0deb6fbf4ee8ff197bfd",
          "sha256": "1c391b3a12e357cd46d31444b3402fcd8c5a48c18cd2b5a31dadef7379c22abf",
          "sha1": "b1ceae44255ef19b99d19a8af3502fdfb7121bfe",
          "md5": "0ffb6e79c1a9ca820b81ec971c8e1f00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-data-1.0.5-sources.jar",
          "url": "ui-tooling-data-1.0.5-sources.jar",
          "size": 7080,
          "sha512": "6ec56272d254bd9c7f151331dced9b4710e3e6ae0a61c29b44f4cf6739b62d40c76a676111dcebcb5906409748732c7f86ba6db9ac79a47c397d7dc48ccb0d64",
          "sha256": "281b6e43679f660b67c0ca187785cc9b5af1bc2e06b9ae652b2b7781c02ad7c3",
          "sha1": "fcb1fd43bc3266c4506d90ed449c51db006b7567",
          "md5": "e39146084c82b742b6ed8072e34f764f"
        }
      ]
    }
  ]
}
